# Generated by Django 5.2.8 on 2025-11-17 13:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show on status page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('stable', 'Stable'), ('degraded', 'Degraded Performance'), ('partial', 'Partial Outage'), ('down', 'Major Outage'), ('maintenance', 'Maintenance')], max_length=20)),
                ('problem', models.TextField(blank=True, help_text='Description of the problem (if any)')),
                ('plan', models.TextField(blank=True, help_text='Plan to resolve the issue (if any)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, max_length=100)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='status.service')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='status_stat_created_273501_idx'), models.Index(fields=['service', '-created_at'], name='status_stat_service_0cc391_idx')],
            },
        ),
    ]
